// ─────────────────────────────────────────────────────────────────────
// Landing Page AI — advertorial pack types.
// Phase 3 — 17 sections, dual-language (MY + VI translation), asset-first.
// ─────────────────────────────────────────────────────────────────────

export type SectionType =
  | 'hero'
  | 'pain'
  | 'why-happens'
  | 'failed-solutions'
  | 'product-discovery'
  | 'ingredients'
  | 'mechanism'
  | 'benefits'
  | 'comparison'            // NEW — product vs competitor infographic
  | 'lifestyle'
  | 'expert-feedback'       // NEW — clinical expert opinion / authority review
  | 'social-proof'
  | 'whatsapp-testimonials'
  | 'news-proof'            // NEW — authority / media proof screenshots
  | 'before-after'          // NEW — transformation photos collage
  | 'faq'
  | 'offer'
  | 'final-cta'

export type LandingLanguage = 'ms' | 'vi' | 'en'

export type LandingForm =
  | 'ugc-malaysia'    // UGC Chuyển Đổi Nhanh — 17-section MY ecommerce advertorial (FROZEN — form 1)
  | 'advertorial'     // Kể Chuyện Hành Trình — editorial / review storytelling
  | 'premium'         // Thương Hiệu Cao Cấp — clean brand, lifestyle, less hard-sell
  | 'hard-sell-cod'   // Chốt Đơn Mạnh — maximum urgency, scarcity, COD aggressive
  | 'chuyen-gia'      // Chuyên Gia / Khoa Học — credibility/infographic/mechanism (Phase 2 stub)

export type CompetitorInfluence = 'low' | 'medium' | 'high'

/** A single uploaded product reference image used as visual memory across
 *  image generations. */
export interface VisualMemoryItem {
  ref: string
  label: string
}

export type ImagePromptStatus = 'idle' | 'queued' | 'generating' | 'retrying' | 'done' | 'failed'

export interface ImagePrompt {
  filename: string
  /** Full English image-generation prompt (30-80 words). Includes text overlay
   *  instructions where required (hero, pain). */
  prompt: string
  /** Style / asset-type label shown as a badge in the UI. */
  style: string
  /** "4:5" / "1:1" / "9:16" / "16:9" */
  aspectRatio: string
  // ── Generated image fields ──────────────────────────────────────────
  generatedAssetRef?: string
  status?: ImagePromptStatus
  error?: string
  /** Z22 — 6-char token seeding the per-image diversity directive. Forces
   *  a unique prompt hash so KIE produces a different latent. Stable across
   *  manual regens (minted once per ImagePrompt). */
  variationSeed?: string
}

export interface FaqItem {
  question: string
  answer: string
}

export interface ReviewItem {
  author: string
  quote: string
  meta?: string
  rating?: number
}

/** Structured comparison schema for `type='comparison'` sections.
 *  Gemini emits this verbatim; KIE consumes it via the structured prompt
 *  builder so the rendered infographic never falls back to regex-parsing
 *  free-form copy ("Không tìm được cặp bullet THEM/US"). */
export interface ComparisonSchema {
  us:   { title: string; bullets: string[] }
  them: { title: string; bullets: string[] }
}

export interface LandingSection {
  type: SectionType
  title: string
  /** Z10b: Vietnamese translation of the section title — shown italic
   *  directly under `title` in the section header bar. Always generated
   *  alongside `title` regardless of output language. */
  titleVi?: string
  copy: string
  layoutGuide: string
  /** Vietnamese translation of `copy` (for the Vietnamese-speaking marketer).
   *  Always included regardless of output language. */
  viTranslation?: string
  /** Section-level aspect ratio — enforced on ALL images in this section.
   *  '1:1' or '4:5' allowed for most sections.
   *  '16:9' allowed ONLY for banner sections (offer / final-cta).
   *  '9:16' allowed ONLY for mobile-screenshot sections
   *    (whatsapp-testimonials + social-proof screenshot variants).
   *    KIE GPT-4o's tallest portrait is 2:3 — we display the card at 9:16
   *    visually and let the mobile-screenshot directive lock composition. */
  imageAspectRatio?: '1:1' | '4:5' | '16:9' | '9:16'
  headline?: string
  subheadline?: string
  cta?: string
  offerStrip?: string
  urgencyText?: string
  bullets?: string[]
  faqs?: FaqItem[]
  reviews?: ReviewItem[]
  imagePrompts: ImagePrompt[]
  imageSizeHint?: string
  // ── Z10: per-field Vietnamese translations (rendered inline under each MY value) ──
  // Always generated when output language ≠ 'vi'. UI hides any *Vi value that
  // equals its source so the VN-output case doesn't show duplicates.
  headlineVi?: string
  subheadlineVi?: string
  ctaVi?: string
  offerStripVi?: string
  urgencyTextVi?: string
  /** Parallel array to `bullets` — same length, index-aligned. */
  bulletsVi?: string[]
  /** Structured comparison data — present ONLY on type='comparison' sections.
   *  Generated by Gemini, consumed by the image prompt finalizer so KIE
   *  receives explicit US-vs-THEM bullet pairs rather than free-form copy. */
  comparisonData?: ComparisonSchema
}

export interface LandingPagePack {
  productId: string
  productName: string
  language: LandingLanguage
  sections: LandingSection[]
  visualMemory: VisualMemoryItem[]
  generatedAt: number
  // ── Phase 3 — form metadata baked onto the pack so downstream image
  // generation can adapt strategy (eg storytelling → character continuity).
  // Optional for backward compat with packs saved before Phase 3.
  form?: LandingForm
  /** Phase 3 storytelling engine — full character profile (name, age,
   *  appearance, environment) shared across all people-shots so the same
   *  person threads through the entire narrative. Set by the advertorial
   *  form module. Other forms leave it undefined. */
  characterProfile?: CharacterProfile
}

/** Storytelling character — one consistent person across all section
 *  imagePrompts. Used by the advertorial form's image continuity engine.
 *  Phase 3 introduces this; later forms (premium narrative variants) may
 *  reuse it. */
export interface CharacterProfile {
  /** Display name — only used in copy, never as a real brand customer. */
  name: string
  /** Locale label e.g. "Malaysian Muslim woman, mid-30s". */
  archetype: string
  /** Compact appearance lock — same description copy-pasted into every
   *  imagePrompt that involves this person. ~80-120 words. */
  appearanceLock: string
  /** Compact environment lock — same home/room context shared across
   *  shots. ~40-80 words. */
  environmentLock: string
  /** Emotional arc points — used to vary expression per section. */
  emotionalArc: { sectionType: string; mood: string }[]
}

export interface LandingGenParams {
  productId: string
  language: LandingLanguage
  form?: LandingForm
  nicheHint?: string
  sourceUrl?: string          // legacy — kept for compat
  competitorUrl?: string      // Step 5: competitor landing page to learn from
  competitorInfluence?: CompetitorInfluence
  visualMemory?: VisualMemoryItem[]
}

export interface SavedLandingPack extends LandingPagePack {
  id: string
  title: string
  createdAt: number
}
