// ─────────────────────────────────────────────────────────────────────
// Chat Proof UI-Native renderer — type contracts.
//
// Architecture: Canvas UI template + AI content injection + AI product
// thumb + screenshot realism post-process. NEVER ask AI to render full
// chat screenshot — that produces warped UI / unreadable text / fake
// icons. Instead we draw pixels deterministically on canvas, then layer
// AI-generated atomic assets (product thumb) into the canvas, then run
// a JPEG-recompress + slight blur post-process for screenshot realism.
// ─────────────────────────────────────────────────────────────────────

/** 5 platform / OS variants the user requested. */
export type ChatProofVariant =
  | 'whatsapp-ios'
  | 'whatsapp-android'
  | 'imessage-ios'
  | 'messenger-ios'
  | 'messenger-android'

/** 4 render layouts the user requested. */
export type ChatProofLayout =
  | 'centered-phone'    // A — phone mockup centered on background (reference image)
  | 'partial-crop'      // B — partial chat-screen crop (no phone frame, soft edge)
  | 'floating-collage'  // C — phone mockup rotated/offset with secondary asset
  | 'full-vertical'     // D — full vertical ad layout (4:5 portrait, phone in upper half)

/** Background style — drawn on canvas behind the phone mockup. */
export type ChatProofBackground =
  | 'dark-gradient'      // black → midnight blue with subtle stars
  | 'ad-creative-grid'   // diagonal yellow/green lines on black (reference image)
  | 'soft-neutral'       // cream / beige soft gradient
  | 'minimal-light'      // pure white / near-white with subtle shadow

/** Phone frame to wrap the chat screen. */
export type PhoneFrame =
  | 'iphone-black'
  | 'iphone-white'
  | 'android-samsung'

/** A single message bubble inside the chat body. */
export interface ChatMessage {
  /** Which side of the conversation this message sits on. */
  side: 'incoming' | 'outgoing'
  /** Message body — supports emoji + line breaks. Kept short (≤ ~80 chars
   *  per line) so text wraps naturally in the bubble. */
  text: string
  /** "9:47", "Khamis 14:23", "Today 9:47 AM" — rendered as a separator
   *  bubble above the message. Optional (most messages don't show one). */
  timestamp?: string
  /** Tail rendering toggle — last bubble in a same-side run gets a tail. */
  hasTail?: boolean
  /** Optional inline emoji reaction (rendered as a small overlay). */
  reaction?: string
}

/** Product card injected as a chat bubble — recreates the iMessage rich-link
 *  preview pattern (see reference image). */
export interface ProductCard {
  /** Pixel data of the product thumbnail — generated by KIE on a small
   *  realistic crop. Stored as a blob URL or asset:xxx ref. */
  thumbnailRef?: string
  /** Bold product title (e.g. "Huel Daily Greens"). */
  title: string
  /** Short subtitle line ("41 vitamins, minerals & superfoods. Just 25 cal."). */
  subtitle: string
  /** Tiny domain text ("huel.com"). */
  domain?: string
  /** Which side of the chat the card sits on. */
  side: 'incoming' | 'outgoing'
}

/** Header row at the top of the chat screen (contact name + avatar). */
export interface ChatHeader {
  /** Display name — Malay name recommended ("Maya", "Aisyah", "Sis Faridah"). */
  contactName: string
  /** Online/last-seen status text. */
  status?: string
  /** Avatar generation hint — color + initials are derived automatically. */
  avatarHint?: string
}

/** Full content payload — everything that gets drawn into the chat body.
 *  Generated by Gemini (text) + KIE (product thumb), then passed to the
 *  canvas renderer. */
export interface ChatProofContent {
  header: ChatHeader
  /** Ordered list of bubbles. The renderer interleaves the product card
   *  at `productCardAfterIndex` (0-based — drawn AFTER this message). */
  messages: ChatMessage[]
  /** Optional product card embedded in the conversation. */
  productCard?: ProductCard
  /** Index in `messages` after which the product card appears. -1 = no card. */
  productCardAfterIndex?: number
}

/** Top-level render spec — passed into renderChatProof(). */
export interface ChatProofSpec {
  variant: ChatProofVariant
  layout: ChatProofLayout
  background: ChatProofBackground
  phoneFrame: PhoneFrame
  content: ChatProofContent
  /** Output dimensions. Defaults to 1080×1350 (4:5 portrait) which
   *  matches landing-page WhatsApp section aspect ratio. */
  width?: number
  height?: number
  /** Post-process intensity — 'subtle' keeps the canvas crisp, 'medium'
   *  adds visible JPEG compression for the "real screenshot" feel. */
  realism?: 'subtle' | 'medium' | 'heavy'
}

/** Result returned by renderChatProof — a Blob the caller can save via
 *  saveAsset() and treat exactly like a KIE-generated image. */
export interface ChatProofResult {
  /** Canvas-rendered final image, post-processed for screenshot realism. */
  blob: Blob
  /** Mime type of `blob` ("image/jpeg" after post-process). */
  mimeType: string
  /** Pixel dimensions. */
  width: number
  height: number
}
