import type { ScriptPreset, ToneOption } from '../types'

// ─────────────────────────────────────────────────────────────────────────
// 15 CLASSIC direct-response UGC ad frameworks. Each preset's 5 fields are
// injected verbatim into the Gemini prompt — they shape hook structure,
// pacing, emotional angle, CTA tone, and proof style.
// ─────────────────────────────────────────────────────────────────────────

const CLASSIC_PRESETS: ScriptPreset[] = [
  {
    id: 'problem-solution',
    label: 'Problem → Solution',
    hint: 'Bạn đang gặp vấn đề này?',
    glyph: '⚡',
    category: 'classic',
    hookFormula: 'Open with a sharp pain point as a direct question — "Anyone else dealing with X?" — that makes the viewer feel called out within the first 2 seconds.',
    pacingNote: 'Fast. Hook → pain agitation → solution within the first 5 seconds. Short clipped sentences.',
    emotionalAngle: 'Recognition and relief. Make the viewer feel "that\'s exactly me" before introducing the fix.',
    ctaStyle: 'Direct and confident — "tap the link, try it, your problem is solved."',
    proofStyle: 'One quick personal result line. No timeline, no science — just outcome.',
  },
  {
    id: 'before-after',
    label: 'Before / After Story',
    hint: 'Tôi từng bị như này…',
    glyph: '↔',
    category: 'classic',
    hookFormula: '"For [time period] I struggled with X..." — open with past pain, then pivot to current win.',
    pacingNote: 'Slow burn buildup. Past pain → turning point → present transformation.',
    emotionalAngle: 'Hope and transformation. The viewer should believe "if it worked for them, it can work for me."',
    ctaStyle: 'Empathetic — "if this is where you are right now, give it a try."',
    proofStyle: 'Personal transformation timeline with one specific marker (number of days, one observable change).',
  },
  {
    id: 'angry-pain',
    label: 'Angry Pain Hook',
    hint: 'Đừng tiếp tục làm điều này…',
    glyph: '🔥',
    category: 'classic',
    hookFormula: '"Stop doing X — it\'s making your problem worse" — contrarian command that interrupts the scroll.',
    pacingNote: 'Punchy and urgent. Every sentence escalates.',
    emotionalAngle: 'Frustration converted into clarity. Validate the viewer\'s anger at failed solutions.',
    ctaStyle: 'Authoritative — "do this instead. Now."',
    proofStyle: 'One counter-intuitive proof point that contradicts a common belief.',
  },
  {
    id: 'doctor-research',
    label: 'Doctor / Research Style',
    hint: 'Có nghiên cứu nói rằng…',
    glyph: '🔬',
    category: 'classic',
    hookFormula: '"A new study found that..." or "Researchers recently discovered..." — lead with cited authority.',
    pacingNote: 'Measured, credible, lecture-light. No yelling. No corporate marketing.',
    emotionalAngle: 'Trust earned through authority and specificity.',
    ctaStyle: 'Soft — "learn more in the link below."',
    proofStyle: 'Specific study reference, percentage, or expert source. No vague "studies show".',
  },
  {
    id: 'friend-rec',
    label: 'Friend Recommendation',
    hint: 'Bạn tôi giới thiệu cái này…',
    glyph: '👯',
    category: 'classic',
    hookFormula: '"My best friend told me about this and I had to try it..." — casual word-of-mouth opener.',
    pacingNote: 'Casual and conversational. Sounds like a voice memo to a friend.',
    emotionalAngle: 'Word-of-mouth trust — the warmest form of social proof.',
    ctaStyle: 'Helpful — "you should genuinely try it, it changed my routine."',
    proofStyle: 'Anecdotal — share the friend\'s observable result, not a stat.',
  },
  {
    id: 'hidden-secret',
    label: 'Hidden Secret / Curiosity',
    hint: 'Không ai nói cho bạn điều này…',
    glyph: '🤫',
    category: 'classic',
    hookFormula: '"No one talks about this but..." or "The thing the industry doesn\'t want you to know..." — open a curiosity loop.',
    pacingNote: 'Conspiratorial. Slow reveal. Pause before payoff.',
    emotionalAngle: 'Curiosity plus insider feeling — the viewer is in on a secret.',
    ctaStyle: 'Mystery-resolution — "tap to see the rest."',
    proofStyle: 'Insider framing — "I only found out because..."',
  },
  {
    id: 'tiktok-pov',
    label: 'TikTok POV',
    hint: 'POV: cuối cùng bạn cũng tìm được…',
    glyph: '📱',
    category: 'classic',
    hookFormula: '"POV: you finally found X..." or "POV: the moment you realize..." — native TikTok meme format.',
    pacingNote: 'Native TikTok rhythm. Short, vibe-driven, lots of natural pauses.',
    emotionalAngle: 'Discovery joy — the satisfying click of finding the right product.',
    ctaStyle: 'Implicit — "this is the one, no more searching."',
    proofStyle: 'Showing not telling. Describe the moment of using the product, not the result.',
  },
  {
    id: 'testimonial',
    label: 'Testimonial Review',
    hint: 'Sau 7 ngày dùng thử…',
    glyph: '⭐',
    category: 'classic',
    hookFormula: '"After [N] days of using X, here\'s what happened..." — open with a defined trial window.',
    pacingNote: 'Day-by-day or week-by-week timeline. Honest pacing — not too enthusiastic.',
    emotionalAngle: 'Earned credibility through real time spent with the product.',
    ctaStyle: 'Honest — "honestly, I\'d recommend it."',
    proofStyle: 'Personal timeline review with at least one specific observed change.',
  },
  {
    id: 'soft-lifestyle',
    label: 'Soft Sell Lifestyle',
    hint: 'Routine mỗi sáng của tôi…',
    glyph: '☕',
    category: 'classic',
    hookFormula: '"My morning routine..." or "Things I can\'t live without..." — soft lifestyle entry.',
    pacingNote: 'Aspirational and calm. No urgency. The product appears naturally.',
    emotionalAngle: 'Belonging and lifestyle aspiration.',
    ctaStyle: 'Light — "everything\'s linked in bio."',
    proofStyle: 'Aesthetic and lifestyle integration — the product belongs in the world the creator is showing.',
  },
  {
    id: 'comparison',
    label: 'Comparison / Callout',
    hint: 'Tôi bỏ sản phẩm cũ vì…',
    glyph: '⚖',
    category: 'classic',
    hookFormula: '"I switched from X to Y because..." — direct contrast with a previous solution.',
    pacingNote: 'Direct contrast. Old vs. new, with one clear winner.',
    emotionalAngle: 'Informed switch — the viewer should feel smarter for choosing.',
    ctaStyle: 'Direct — "try the switch, you won\'t go back."',
    proofStyle: 'Side-by-side comparison logic with one clearly better attribute.',
  },
  {
    id: 'emotional-story',
    label: 'Emotional Storytelling',
    hint: 'Tôi đã mất tự tin vì…',
    glyph: '💗',
    category: 'classic',
    hookFormula: '"I lost my confidence because of..." or "For years I felt..." — vulnerability open.',
    pacingNote: 'Slow and reflective, building to relief. Real emotional pauses.',
    emotionalAngle: 'Shared vulnerability — the viewer should feel seen.',
    ctaStyle: 'Gentle — "if you feel this too, this helped me."',
    proofStyle: 'Personal narrative arc — a specific emotional turning point, not a stat.',
  },
  {
    id: 'fast-cta',
    label: 'Fast CTA Conversion',
    hint: 'Nếu bạn đang gặp vấn đề này…',
    glyph: '⏱',
    category: 'classic',
    hookFormula: '"If you have X, you NEED to see this" — direct match-to-pain in the first sentence.',
    pacingNote: 'Speed-run. Ideal under 15 seconds. No wasted words.',
    emotionalAngle: 'Urgency. The viewer should feel they need to act now.',
    ctaStyle: 'Hard — "tap the link now, link in bio."',
    proofStyle: 'Skip proof — go straight to CTA. The match-to-pain is the proof.',
  },
  {
    id: 'native-selfie',
    label: 'Native Selfie UGC',
    hint: 'Như video selfie thật',
    glyph: '🤳',
    category: 'classic',
    hookFormula: 'Casual unscripted opener — "Guys I just have to talk about this..." or "Ok wait this is wild..." — like the camera caught them mid-thought.',
    pacingNote: 'Imperfect, native, slightly rambling. The kind of cadence a real person uses on the front camera.',
    emotionalAngle: 'Authenticity and realness — no produced feeling.',
    ctaStyle: 'Casual — "go check it out, link in bio."',
    proofStyle: 'Off-the-cuff anecdote — sound like the creator is just remembering it.',
  },
  {
    id: 'pattern-interrupt',
    label: 'Viral Pattern Interrupt',
    hint: 'Mở đầu lạ / gây tò mò',
    glyph: '⚠',
    category: 'classic',
    hookFormula: 'Weird or contrarian first line — "Don\'t buy this if you..." or "I was wrong about this..." — break the scroll pattern.',
    pacingNote: 'Fast cut after the hook, then explain. The hook is a hand-grenade — explain after the bang.',
    emotionalAngle: 'Curiosity through pattern break.',
    ctaStyle: 'Twist — "still curious? tap the link."',
    proofStyle: 'Counter-intuitive reveal — the explanation flips the assumption.',
  },
  {
    id: 'authority-proof',
    label: 'Authority + Social Proof',
    hint: '10,000+ người đã chuyển sang…',
    glyph: '🏆',
    category: 'classic',
    hookFormula: '"10,000+ people already switched to X..." — lead with a believable number.',
    pacingNote: 'Authoritative buildup. Confident, not loud.',
    emotionalAngle: 'Bandwagon plus FOMO — viewer should feel they\'re late.',
    ctaStyle: 'Confident — "join them, tap the link."',
    proofStyle: 'Numbers, ratings, and mass adoption signals.',
  },
]

// ─────────────────────────────────────────────────────────────────────────
// 7 EDUCATIONAL presets — used for skincare / supplement / wellness ads
// where conversion depends on the viewer UNDERSTANDING the mechanism. These
// presets automatically trigger educationalMode behaviour in the prompt.
// ─────────────────────────────────────────────────────────────────────────

const EDUCATIONAL_PRESETS: ScriptPreset[] = [
  {
    id: 'edu-ingredient',
    label: 'Ingredient Education',
    hint: 'Ramai orang tak tahu fungsi bahan ni…',
    glyph: '🧪',
    category: 'educational',
    hookFormula: '"Most people don\'t actually know what X does..." — open by educating about an ingredient.',
    pacingNote: 'Calm explainer rhythm. Friend-to-friend, not lecture.',
    emotionalAngle: 'Empowered understanding — the viewer leaves smarter.',
    ctaStyle: 'Educational — "now that you know, here\'s where to find it."',
    proofStyle: 'Plain-language ingredient explanation. No medical jargon. Compare to something familiar.',
  },
  {
    id: 'edu-scientific',
    label: 'Scientific Explainer',
    hint: 'Actually masalah ni berlaku sebab…',
    glyph: '📖',
    category: 'educational',
    hookFormula: '"Here\'s why this actually happens..." — mechanism-first opening.',
    pacingNote: 'Lecture-style but conversational. Spoken, not written.',
    emotionalAngle: 'Trust through understanding the root cause.',
    ctaStyle: 'Soft — "now you know how to fix it."',
    proofStyle: 'Cause-effect mechanism explained in plain creator language.',
  },
  {
    id: 'edu-mechanism',
    label: 'Mechanism Breakdown',
    hint: 'Cách sản phẩm này hoạt động',
    glyph: '⚙',
    category: 'educational',
    hookFormula: '"How does X actually work? Let me break it down..." — promise a useful explainer.',
    pacingNote: 'Step-by-step. Each step short. Use linking phrases like "and then..."',
    emotionalAngle: 'Logical confidence — the viewer should understand the chain.',
    ctaStyle: 'Reasoned — "now you understand why this works."',
    proofStyle: 'Step-by-step mechanism with the key ingredient(s) named at each step.',
  },
  {
    id: 'edu-myth',
    label: 'Myth Busting',
    hint: 'Bukan semua probiotic sama…',
    glyph: '❌',
    category: 'educational',
    hookFormula: '"Most X are not actually the same — here\'s the real difference..." — contrarian education.',
    pacingNote: 'Contrarian setup followed by clear differentiation.',
    emotionalAngle: 'Informed superiority — the viewer feels smarter than the average buyer.',
    ctaStyle: 'Smart choice — "the one that actually works is the one in the link."',
    proofStyle: 'Category vs. specific product — contrast the generic vs. this specific formula.',
  },
  {
    id: 'edu-deep-problem',
    label: 'Deep Problem Awareness',
    hint: 'Punca sebenar bukan apa anda fikir…',
    glyph: '🎯',
    category: 'educational',
    hookFormula: '"The real cause isn\'t what you think..." — reveal a deeper root cause.',
    pacingNote: 'Revelation buildup — old belief → real cause → solution.',
    emotionalAngle: 'Surprise then relief — "no wonder nothing was working."',
    ctaStyle: 'Solution-pointed — "this is the only one that addresses the real cause."',
    proofStyle: 'Root-cause logic linking the unexpected mechanism to the visible symptom.',
  },
  {
    id: 'edu-spotlight',
    label: 'Ingredient Spotlight',
    hint: 'Tập trung 1 hero ingredient',
    glyph: '💎',
    category: 'educational',
    hookFormula: 'Lead with the hero ingredient by name — "X is the ingredient changing how I think about Y..."',
    pacingNote: 'Deep dive on one ingredient — what it is, how it works, why it matters.',
    emotionalAngle: 'Discovery of a star ingredient.',
    ctaStyle: 'Specific — "look for X on the label, this product has it."',
    proofStyle: 'Single ingredient deep proof — origin, mechanism, and observable effect.',
  },
  {
    id: 'edu-research-ugc',
    label: 'Research-backed UGC',
    hint: 'Creator + giải thích khoa học',
    glyph: '🎓',
    category: 'educational',
    hookFormula: '"I read a study about this and I had to share..." — creator-as-researcher voice.',
    pacingNote: 'Casual but informative — the creator did the homework so the viewer doesn\'t have to.',
    emotionalAngle: 'Smart-creator authority — trusted because they explained it well.',
    ctaStyle: 'Recommendation — "honestly, I\'d try it after reading this."',
    proofStyle: 'Creator-reported research distilled into one or two plain takeaways.',
  },
]

export const SCRIPT_PRESETS: ScriptPreset[] = [...CLASSIC_PRESETS, ...EDUCATIONAL_PRESETS]

export function getPresetById(id: string): ScriptPreset | undefined {
  return SCRIPT_PRESETS.find((p) => p.id === id)
}

// ── Tone modifier chips ─────────────────────────────────────────────────

export const TONE_OPTIONS: ToneOption[] = [
  { id: 'hard-sell',         label: 'Hard sell',          promptHint: 'aggressive sales energy with urgency and direct asks' },
  { id: 'soft-sell',         label: 'Soft sell',          promptHint: 'low-pressure, helpful-friend energy — recommend without pushing' },
  { id: 'emotional',         label: 'Cảm xúc',            promptHint: 'lean into emotional storytelling and vulnerability' },
  { id: 'scientific',        label: 'Khoa học',           promptHint: 'cite mechanism and ingredients with plain-language science' },
  { id: 'funny',             label: 'Hài hước',           promptHint: 'light humour and self-deprecating moments — never cringe' },
  { id: 'luxury',            label: 'Sang trọng',         promptHint: 'premium aspirational tone, refined word choice, calm pacing' },
  { id: 'aggressive-hook',   label: 'Hook gắt',           promptHint: 'sharper, more provocative hook that interrupts the scroll' },
  { id: 'female-audience',   label: 'Nữ',                 promptHint: 'addressing a female viewer — pain points and language framed for her' },
  { id: 'male-audience',     label: 'Nam',                promptHint: 'addressing a male viewer — direct, no-fluff, results-focused' },
  { id: 'older-audience',    label: 'Trung niên',         promptHint: 'older audience (35+) — slower pacing, trust signals, less slang' },
  { id: 'young-tiktok',      label: 'Gen Z TikTok',       promptHint: 'Gen Z TikTok voice — fast cuts, slang, native creator rhythm' },
]
