import type { ScriptPreset, ToneOption } from '../types'

// ─────────────────────────────────────────────────────────────────────────
// 15 CLASSIC direct-response UGC ad frameworks. Each preset's 5 fields are
// injected verbatim into the Gemini prompt — they shape hook structure,
// pacing, emotional angle, CTA tone, and proof style.
// ─────────────────────────────────────────────────────────────────────────

const CLASSIC_PRESETS: ScriptPreset[] = [
  {
    id: 'problem-solution',
    label: 'Problem → Solution',
    hint: 'Bạn đang gặp vấn đề này?',
    glyph: '⚡',
    category: 'classic',
    hookFormula: 'Open with a sharp pain point as a direct question — "Anyone else dealing with X?" — that makes the viewer feel called out within the first 2 seconds.',
    pacingNote: 'Fast. Hook → pain agitation → solution within the first 5 seconds. Short clipped sentences.',
    emotionalAngle: 'Recognition and relief. Make the viewer feel "that\'s exactly me" before introducing the fix.',
    ctaStyle: 'Direct and confident — "tap the link, try it, your problem is solved."',
    proofStyle: 'One quick personal result line. No timeline, no science — just outcome.',
    detailVi: {
      mechanism: 'Mở đầu bằng câu hỏi đánh trúng đúng nỗi đau, đẩy nhanh xuống giải pháp trong 5 giây đầu. Tạo cảm giác "đúng là mình" rồi giới thiệu sản phẩm.',
      goals: ['Hook trực diện 3 giây đầu', 'Khớp đúng nỗi đau của khán giả', 'Tập trung chuyển đổi, không kể lể'],
      useCase: ['Sản phẩm giải quyết nỗi đau phổ biến', 'Khán giả đã nhận ra vấn đề', 'Quảng cáo cold traffic ngắn 15-30 giây'],
      example: '"Có ai cũng bị đầy hơi sau mỗi bữa ăn như mình không?"',
    },
  },
  {
    id: 'before-after',
    label: 'Before / After Story',
    hint: 'Tôi từng bị như này…',
    glyph: '↔',
    category: 'classic',
    hookFormula: '"For [time period] I struggled with X..." — open with past pain, then pivot to current win.',
    pacingNote: 'Slow burn buildup. Past pain → turning point → present transformation.',
    emotionalAngle: 'Hope and transformation. The viewer should believe "if it worked for them, it can work for me."',
    ctaStyle: 'Empathetic — "if this is where you are right now, give it a try."',
    proofStyle: 'Personal transformation timeline with one specific marker (number of days, one observable change).',
    detailVi: {
      mechanism: 'Kể câu chuyện chuyển hoá: quá khứ đau → bước ngoặt → hiện tại tốt hơn. Tạo cảm giác "họ làm được thì mình cũng làm được".',
      goals: ['Tạo đồng cảm sâu với khán giả', 'Chứng minh kết quả qua thời gian thực tế', 'Giảm rào cản tin tưởng'],
      useCase: ['Sản phẩm có sự chuyển hoá rõ (skincare, supplement, fitness)', 'Khán giả cần thấy bằng chứng từ từ', 'Quảng cáo 30-60 giây'],
      example: '"Suốt 3 năm mình vật lộn với mụn người lớn — cho đến khi thử cái này."',
    },
  },
  {
    id: 'angry-pain',
    label: 'Angry Pain Hook',
    hint: 'Đừng tiếp tục làm điều này…',
    glyph: '🔥',
    category: 'classic',
    hookFormula: '"Stop doing X — it\'s making your problem worse" — contrarian command that interrupts the scroll.',
    pacingNote: 'Punchy and urgent. Every sentence escalates.',
    emotionalAngle: 'Frustration converted into clarity. Validate the viewer\'s anger at failed solutions.',
    ctaStyle: 'Authoritative — "do this instead. Now."',
    proofStyle: 'One counter-intuitive proof point that contradicts a common belief.',
    detailVi: {
      mechanism: 'Ra lệnh ngược ("Đừng làm X nữa") để chặn scroll, sau đó giải thích vì sao và đưa giải pháp đúng. Khai thác sự bực bội tích luỹ.',
      goals: ['Chặn scroll bằng lời nói ngược', 'Khai thác sự bực bội với giải pháp rởm', 'Định vị uy quyền cho thương hiệu'],
      useCase: ['Ngành có nhiều sản phẩm giả / kém chất lượng', 'Khán giả đã thử nhiều thứ không hiệu quả', 'Phong cách advertorial gay gắt'],
      example: '"Đừng uống trà detox nữa — nó đang làm bụng bạn đầy hơi hơn đấy."',
    },
  },
  {
    id: 'doctor-research',
    label: 'Doctor / Research Style',
    hint: 'Có nghiên cứu nói rằng…',
    glyph: '🔬',
    category: 'classic',
    hookFormula: '"A new study found that..." or "Researchers recently discovered..." — lead with cited authority.',
    pacingNote: 'Measured, credible, lecture-light. No yelling. No corporate marketing.',
    emotionalAngle: 'Trust earned through authority and specificity.',
    ctaStyle: 'Soft — "learn more in the link below."',
    proofStyle: 'Specific study reference, percentage, or expert source. No vague "studies show".',
    detailVi: {
      mechanism: 'Trích nghiên cứu / góc nhìn chuyên gia để tăng độ tin cậy. Giảm cảm giác "đây là quảng cáo", đẩy lên cảm giác "thông tin hữu ích".',
      goals: ['Tăng độ tin tưởng', 'Định vị sản phẩm có cơ sở khoa học', 'Giảm rào cản với mức giá cao'],
      useCase: ['Supplement / sức khoẻ', 'Skincare có công bố thành phần', 'Sản phẩm giá trị đơn hàng cao cần niềm tin'],
      example: '"Nghiên cứu mới phát hiện 80% trường hợp đầy hơi là do mất cân bằng vi khuẩn đường ruột."',
    },
  },
  {
    id: 'friend-rec',
    label: 'Friend Recommendation',
    hint: 'Bạn tôi giới thiệu cái này…',
    glyph: '👯',
    category: 'classic',
    hookFormula: '"My best friend told me about this and I had to try it..." — casual word-of-mouth opener.',
    pacingNote: 'Casual and conversational. Sounds like a voice memo to a friend.',
    emotionalAngle: 'Word-of-mouth trust — the warmest form of social proof.',
    ctaStyle: 'Helpful — "you should genuinely try it, it changed my routine."',
    proofStyle: 'Anecdotal — share the friend\'s observable result, not a stat.',
    detailVi: {
      mechanism: 'Giọng kể bạn-tới-bạn ("Bạn tôi giới thiệu cái này…"). Truyền miệng là dạng bằng chứng xã hội ấm và thuyết phục nhất.',
      goals: ['Loại bỏ cảm giác quảng cáo', 'Tạo niềm tin qua câu chuyện cá nhân', 'Tăng chuyển đổi nhờ sự gần gũi'],
      useCase: ['Beauty / wellness', 'Sản phẩm hay được chia sẻ trong nhóm bạn', 'Khán giả nữ 20-35'],
      example: '"Đứa bạn cứ khen cái này hoài, mình đành phải thử."',
    },
  },
  {
    id: 'hidden-secret',
    label: 'Hidden Secret / Curiosity',
    hint: 'Không ai nói cho bạn điều này…',
    glyph: '🤫',
    category: 'classic',
    hookFormula: '"No one talks about this but..." or "The thing the industry doesn\'t want you to know..." — open a curiosity loop.',
    pacingNote: 'Conspiratorial. Slow reveal. Pause before payoff.',
    emotionalAngle: 'Curiosity plus insider feeling — the viewer is in on a secret.',
    ctaStyle: 'Mystery-resolution — "tap to see the rest."',
    proofStyle: 'Insider framing — "I only found out because..."',
    detailVi: {
      mechanism: 'Mở vòng tò mò ("Không ai nói cho bạn điều này…"). Khiến khán giả cảm thấy mình "trong cuộc", phải xem hết để biết bí mật.',
      goals: ['Tăng thời gian xem nhờ sự tò mò', 'CTR cao nhờ yếu tố bí ẩn', 'Tiết lộ cuối → dẫn về CTA'],
      useCase: ['Sản phẩm có cơ chế lạ, ít người biết', 'Ngành cạnh tranh cao', 'Khán giả thích mẹo "trong cuộc"'],
      example: '"Có 1 điều ngành mỹ phẩm không muốn bạn biết về thành phần này…"',
    },
  },
  {
    id: 'tiktok-pov',
    label: 'TikTok POV',
    hint: 'POV: cuối cùng bạn cũng tìm được…',
    glyph: '📱',
    category: 'classic',
    hookFormula: '"POV: you finally found X..." or "POV: the moment you realize..." — native TikTok meme format.',
    pacingNote: 'Native TikTok rhythm. Short, vibe-driven, lots of natural pauses.',
    emotionalAngle: 'Discovery joy — the satisfying click of finding the right product.',
    ctaStyle: 'Implicit — "this is the one, no more searching."',
    proofStyle: 'Showing not telling. Describe the moment of using the product, not the result.',
    detailVi: {
      mechanism: 'Dùng định dạng POV thuần TikTok ("POV: cuối cùng bạn cũng tìm được…"). Tận dụng nhịp meme có sẵn để hoà vào feed một cách tự nhiên.',
      goals: ['Hoà vào dòng feed organic', 'Giữ chân người xem nhờ định dạng quen thuộc', 'Khơi gợi cảm giác "tìm được rồi"'],
      useCase: ['Khán giả Gen Z / Millennial', 'TikTok organic + chạy quảng cáo', 'Sản phẩm lifestyle / beauty'],
      example: '"POV: cuối cùng cũng tìm được kem dưỡng dành cho da dầu thật sự dùng được."',
    },
  },
  {
    id: 'testimonial',
    label: 'Testimonial Review',
    hint: 'Sau 7 ngày dùng thử…',
    glyph: '⭐',
    category: 'classic',
    hookFormula: '"After [N] days of using X, here\'s what happened..." — open with a defined trial window.',
    pacingNote: 'Day-by-day or week-by-week timeline. Honest pacing — not too enthusiastic.',
    emotionalAngle: 'Earned credibility through real time spent with the product.',
    ctaStyle: 'Honest — "honestly, I\'d recommend it."',
    proofStyle: 'Personal timeline review with at least one specific observed change.',
    detailVi: {
      mechanism: 'Review có mốc thời gian cụ thể ("Sau 7 ngày…"). Tin tưởng đến từ kết quả cá nhân quan sát được, không phải hứa hẹn lớn lao.',
      goals: ['Tạo uy tín bằng trải nghiệm thật', 'Đặt kỳ vọng thực tế cho người mua', 'Giảm sự hoài nghi'],
      useCase: ['Sản phẩm cần thời gian thấy kết quả', 'Giá trị đơn hàng trung-cao', 'Khán giả kỹ tính, hay so sánh'],
      example: '"Sau 14 ngày dùng serum này, đây là những gì thật sự đã thay đổi."',
    },
  },
  {
    id: 'soft-lifestyle',
    label: 'Soft Sell Lifestyle',
    hint: 'Routine mỗi sáng của tôi…',
    glyph: '☕',
    category: 'classic',
    hookFormula: '"My morning routine..." or "Things I can\'t live without..." — soft lifestyle entry.',
    pacingNote: 'Aspirational and calm. No urgency. The product appears naturally.',
    emotionalAngle: 'Belonging and lifestyle aspiration.',
    ctaStyle: 'Light — "everything\'s linked in bio."',
    proofStyle: 'Aesthetic and lifestyle integration — the product belongs in the world the creator is showing.',
    detailVi: {
      mechanism: 'Mở đầu kiểu lifestyle khát vọng — sản phẩm xuất hiện tự nhiên trong morning routine. Không bán, chỉ show — khán giả tự muốn join lifestyle đó.',
      goals: ['Tạo cảm giác "muốn có cuộc sống như vậy"', 'CTA mềm, dành cho top-of-funnel', 'Gắn thương hiệu vào lối sống mong muốn'],
      useCase: ['Sản phẩm cao cấp / thẩm mỹ', 'Khán giả nữ thích lifestyle', 'Giai đoạn nhận diện thương hiệu'],
      example: '"Morning routine của mình — cà phê, nắng sớm, và 1 nghi thức nhỏ này."',
    },
  },
  {
    id: 'comparison',
    label: 'Comparison / Callout',
    hint: 'Tôi bỏ sản phẩm cũ vì…',
    glyph: '⚖',
    category: 'classic',
    hookFormula: '"I switched from X to Y because..." — direct contrast with a previous solution.',
    pacingNote: 'Direct contrast. Old vs. new, with one clear winner.',
    emotionalAngle: 'Informed switch — the viewer should feel smarter for choosing.',
    ctaStyle: 'Direct — "try the switch, you won\'t go back."',
    proofStyle: 'Side-by-side comparison logic with one clearly better attribute.',
    detailVi: {
      mechanism: 'Câu chuyện đổi sản phẩm ("Tôi bỏ X vì…"). Định vị sản phẩm là lựa chọn thông minh — khán giả cảm thấy mình hiểu biết khi mua theo.',
      goals: ['Đối đầu trực tiếp với sản phẩm dẫn đầu ngành', 'Kích hoạt sự cân nhắc đổi sản phẩm', 'Cho khán giả cảm giác "đang nâng cấp"'],
      useCase: ['Ngành đông đối thủ', 'Sản phẩm có USP rõ ràng', 'Re-targeting / mid-funnel'],
      example: '"Mình bỏ chai kem 2 triệu để đổi sang cái này — và không hề hối hận."',
    },
  },
  {
    id: 'emotional-story',
    label: 'Emotional Storytelling',
    hint: 'Tôi đã mất tự tin vì…',
    glyph: '💗',
    category: 'classic',
    hookFormula: '"I lost my confidence because of..." or "For years I felt..." — vulnerability open.',
    pacingNote: 'Slow and reflective, building to relief. Real emotional pauses.',
    emotionalAngle: 'Shared vulnerability — the viewer should feel seen.',
    ctaStyle: 'Gentle — "if you feel this too, this helped me."',
    proofStyle: 'Personal narrative arc — a specific emotional turning point, not a stat.',
    detailVi: {
      mechanism: 'Mở đầu bằng sự yếu đuối ("Tôi đã mất tự tin vì…"). Tạo đồng cảm sâu, slow-burn từ tổn thương đến giải thoát.',
      goals: ['Tạo đồng cảm rất sâu', 'Giữ chân người xem cho video dài', 'Xây dựng tình cảm với thương hiệu'],
      useCase: ['Sản phẩm liên quan tự tin (da, tóc, body)', 'Khán giả từng tổn thương về ngoại hình', 'Khán giả nữ 25-45'],
      example: '"Mình từng không dám ra ngoài suốt 2 năm vì da mặt."',
    },
  },
  {
    id: 'fast-cta',
    label: 'Fast CTA Conversion',
    hint: 'Nếu bạn đang gặp vấn đề này…',
    glyph: '⏱',
    category: 'classic',
    hookFormula: '"If you have X, you NEED to see this" — direct match-to-pain in the first sentence.',
    pacingNote: 'Speed-run. Ideal under 15 seconds. No wasted words.',
    emotionalAngle: 'Urgency. The viewer should feel they need to act now.',
    ctaStyle: 'Hard — "tap the link now, link in bio."',
    proofStyle: 'Skip proof — go straight to CTA. The match-to-pain is the proof.',
    detailVi: {
      mechanism: 'Câu đầu khớp đúng nỗi đau, đẩy thẳng CTA — không kể chuyện, không proof. Chốt đơn nhanh cho khán giả đã warm.',
      goals: ['CTR tối đa cho video ngắn', 'Re-target khán giả ở đáy phễu', 'Phản hồi trực tiếp, không vòng vo'],
      useCase: ['Re-targeting khán giả đã từng tương tác', 'Flash sale / khuyến mãi gấp', 'Đã có bằng chứng từ quảng cáo phía trước'],
      example: '"Nếu bạn đang bị đầy hơi, bạn BẮT BUỘC phải xem cái này — link in bio."',
    },
  },
  {
    id: 'native-selfie',
    label: 'Native Selfie UGC',
    hint: 'Như video selfie thật',
    glyph: '🤳',
    category: 'classic',
    hookFormula: 'Casual unscripted opener — "Guys I just have to talk about this..." or "Ok wait this is wild..." — like the camera caught them mid-thought.',
    pacingNote: 'Imperfect, native, slightly rambling. The kind of cadence a real person uses on the front camera.',
    emotionalAngle: 'Authenticity and realness — no produced feeling.',
    ctaStyle: 'Casual — "go check it out, link in bio."',
    proofStyle: 'Off-the-cuff anecdote — sound like the creator is just remembering it.',
    detailVi: {
      mechanism: 'Giống video selfie thật, hơi lan man ("Ê mọi người, mình phải kể cái này…"). Loại bỏ cảm giác quảng cáo, tăng sự chân thật.',
      goals: ['Cảm giác chân thật tối đa', 'Hoà vào dòng feed tự nhiên', 'Tăng chuyển đổi nhờ tin tưởng'],
      useCase: ['TikTok organic', 'Quảng cáo creator whitelisted', 'Khán giả đã cảnh giác với quảng cáo'],
      example: '"Ê khoan — mình vừa phát hiện cái này mà cứ nghĩ hoài không thôi được."',
    },
  },
  {
    id: 'pattern-interrupt',
    label: 'Viral Pattern Interrupt',
    hint: 'Mở đầu lạ / gây tò mò',
    glyph: '⚠',
    category: 'classic',
    hookFormula: 'Weird or contrarian first line — "Don\'t buy this if you..." or "I was wrong about this..." — break the scroll pattern.',
    pacingNote: 'Fast cut after the hook, then explain. The hook is a hand-grenade — explain after the bang.',
    emotionalAngle: 'Curiosity through pattern break.',
    ctaStyle: 'Twist — "still curious? tap the link."',
    proofStyle: 'Counter-intuitive reveal — the explanation flips the assumption.',
    detailVi: {
      mechanism: 'Câu mở đầu lạ / trái kỳ vọng ("Đừng mua sản phẩm này nếu…"). Hook nổ như lựu đạn để chặn scroll — giải thích NGAY sau cú nổ.',
      goals: ['Chặn scroll tối đa trong 3 giây đầu', 'Tăng CTR mạnh', 'Nổi bật trên feed dày đặc quảng cáo'],
      useCase: ['Cold traffic khó tiếp cận', 'Khán giả đã "miễn dịch" với quảng cáo', 'Thương hiệu mới cần phá vỡ rào cản'],
      example: '"Đừng mua serum này nếu bạn thật sự thích da sáng sau 1 đêm."',
    },
  },
  {
    id: 'authority-proof',
    label: 'Authority + Social Proof',
    hint: '10,000+ người đã chuyển sang…',
    glyph: '🏆',
    category: 'classic',
    hookFormula: '"10,000+ people already switched to X..." — lead with a believable number.',
    pacingNote: 'Authoritative buildup. Confident, not loud.',
    emotionalAngle: 'Bandwagon plus FOMO — viewer should feel they\'re late.',
    ctaStyle: 'Confident — "join them, tap the link."',
    proofStyle: 'Numbers, ratings, and mass adoption signals.',
    detailVi: {
      mechanism: 'Dẫn số liệu lớn ("10,000+ người đã chuyển sang…"). Kích hoạt tâm lý đám đông + FOMO — khán giả cảm thấy mình đang chậm chân.',
      goals: ['Bằng chứng xã hội ở quy mô lớn', 'Tâm lý đám đông + FOMO', 'Niềm tin nhờ nhiều người đã dùng'],
      useCase: ['Thương hiệu đã có lượng đơn hàng lớn', 'Giai đoạn re-launch / scale', 'Ngành dựa vào niềm tin'],
      example: '"Hơn 10,000 người Malaysia đã chuyển sang công thức này — đây là lý do."',
    },
  },
]

// ─────────────────────────────────────────────────────────────────────────
// 7 EDUCATIONAL presets — used for skincare / supplement / wellness ads
// where conversion depends on the viewer UNDERSTANDING the mechanism. These
// presets automatically trigger educationalMode behaviour in the prompt.
// ─────────────────────────────────────────────────────────────────────────

const EDUCATIONAL_PRESETS: ScriptPreset[] = [
  {
    id: 'edu-ingredient',
    label: 'Ingredient Education',
    hint: 'Ramai orang tak tahu fungsi bahan ni…',
    glyph: '🧪',
    category: 'educational',
    hookFormula: '"Most people don\'t actually know what X does..." — open by educating about an ingredient.',
    pacingNote: 'Calm explainer rhythm. Friend-to-friend, not lecture.',
    emotionalAngle: 'Empowered understanding — the viewer leaves smarter.',
    ctaStyle: 'Educational — "now that you know, here\'s where to find it."',
    proofStyle: 'Plain-language ingredient explanation. No medical jargon. Compare to something familiar.',
    detailVi: {
      mechanism: 'Giáo dục về thành phần ("Ít người biết thật sự X làm gì"). Giải thích kiểu bạn-tới-bạn, không lên lớp — khán giả ra về cảm thấy mình thông minh hơn.',
      goals: ['Cảm giác được trao kiến thức', 'Niềm tin nhờ hiểu rõ', 'Hợp lý hoá mức giá cao'],
      useCase: ['Sản phẩm có thành phần đặc biệt', 'Khán giả nghiên cứu kỹ trước khi mua', 'Sức khoẻ / skincare / supplement'],
      example: '"Mọi người ít ai biết Inulin thật sự làm gì — để mình giải thích nhé."',
    },
  },
  {
    id: 'edu-scientific',
    label: 'Scientific Explainer',
    hint: 'Actually masalah ni berlaku sebab…',
    glyph: '📖',
    category: 'educational',
    hookFormula: '"Here\'s why this actually happens..." — mechanism-first opening.',
    pacingNote: 'Lecture-style but conversational. Spoken, not written.',
    emotionalAngle: 'Trust through understanding the root cause.',
    ctaStyle: 'Soft — "now you know how to fix it."',
    proofStyle: 'Cause-effect mechanism explained in plain creator language.',
    detailVi: {
      mechanism: 'Đi thẳng vào cơ chế ("Sự thật là vấn đề này xảy ra vì…"). Giải thích nguyên nhân-kết quả bằng ngôn ngữ đời thường, không dùng thuật ngữ y học.',
      goals: ['Hiểu được nguyên nhân gốc', 'Niềm tin nhờ nhận thức mới', 'Giảm sự bối rối về vấn đề'],
      useCase: ['Ngành sức khoẻ có nhiều quan niệm sai', 'Khán giả đang bối rối về nguyên nhân', 'Phong cách advertorial'],
      example: '"Thật ra, đầy hơi thường xảy ra vì hệ vi khuẩn đường ruột mất cân bằng."',
    },
  },
  {
    id: 'edu-mechanism',
    label: 'Mechanism Breakdown',
    hint: 'Cách sản phẩm này hoạt động',
    glyph: '⚙',
    category: 'educational',
    hookFormula: '"How does X actually work? Let me break it down..." — promise a useful explainer.',
    pacingNote: 'Step-by-step. Each step short. Use linking phrases like "and then..."',
    emotionalAngle: 'Logical confidence — the viewer should understand the chain.',
    ctaStyle: 'Reasoned — "now you understand why this works."',
    proofStyle: 'Step-by-step mechanism with the key ingredient(s) named at each step.',
    detailVi: {
      mechanism: 'Giải thích từng bước ("Sản phẩm này hoạt động ra sao? Để mình giải thích…"). Mỗi bước ngắn, logic liền mạch.',
      goals: ['Tạo sự tự tin nhờ logic', 'Hợp lý hoá cơ chế của sản phẩm', 'Giáo dục khán giả kỹ tính'],
      useCase: ['Sản phẩm có cơ chế độc đáo', 'Khán giả trung niên / lớn tuổi', 'Giá trị đơn hàng cao'],
      example: '"Đây là cách nó hoạt động — đầu tiên, các chủng lợi khuẩn bám vào…"',
    },
  },
  {
    id: 'edu-myth',
    label: 'Myth Busting',
    hint: 'Bukan semua probiotic sama…',
    glyph: '❌',
    category: 'educational',
    hookFormula: '"Most X are not actually the same — here\'s the real difference..." — contrarian education.',
    pacingNote: 'Contrarian setup followed by clear differentiation.',
    emotionalAngle: 'Informed superiority — the viewer feels smarter than the average buyer.',
    ctaStyle: 'Smart choice — "the one that actually works is the one in the link."',
    proofStyle: 'Category vs. specific product — contrast the generic vs. this specific formula.',
    detailVi: {
      mechanism: 'Phá bỏ niềm tin sai phổ biến ("Không phải probiotic nào cũng giống nhau"). Định vị sản phẩm khác hẳn ngành — khán giả thấy mình là "người mua hiểu biết".',
      goals: ['Cảm giác "mình biết nhiều hơn người khác"', 'Phân biệt sản phẩm rõ ràng', 'Kích hoạt lựa chọn thông minh'],
      useCase: ['Ngành bị thương mại hoá tràn lan', 'Có USP kỹ thuật rõ', 'Khán giả đã ngán ngành hàng'],
      example: '"Không phải probiotic nào cũng giống nhau — đa phần không sống nổi qua axit dạ dày."',
    },
  },
  {
    id: 'edu-deep-problem',
    label: 'Deep Problem Awareness',
    hint: 'Punca sebenar bukan apa anda fikir…',
    glyph: '🎯',
    category: 'educational',
    hookFormula: '"The real cause isn\'t what you think..." — reveal a deeper root cause.',
    pacingNote: 'Revelation buildup — old belief → real cause → solution.',
    emotionalAngle: 'Surprise then relief — "no wonder nothing was working."',
    ctaStyle: 'Solution-pointed — "this is the only one that addresses the real cause."',
    proofStyle: 'Root-cause logic linking the unexpected mechanism to the visible symptom.',
    detailVi: {
      mechanism: 'Tiết lộ nguyên nhân thật ("Nguyên nhân thật sự không phải cái bạn nghĩ"). Bất ngờ → nhẹ nhõm → giải pháp. Giải thích vì sao các giải pháp cũ thất bại.',
      goals: ['Định nghĩa lại vấn đề', 'Lý giải vì sao các giải pháp khác thất bại', 'Định vị sản phẩm là "duy nhất hoạt động được"'],
      useCase: ['Khán giả đã thử nhiều thứ không hiệu quả', 'Vấn đề phức tạp trong ngành', 'Advertorial dài 45-60 giây'],
      example: '"Nguyên nhân thật sự khiến da bạn bị nổi mụn không phải cái bạn nghĩ — nó sâu hơn nhiều."',
    },
  },
  {
    id: 'edu-spotlight',
    label: 'Ingredient Spotlight',
    hint: 'Tập trung 1 hero ingredient',
    glyph: '💎',
    category: 'educational',
    hookFormula: 'Lead with the hero ingredient by name — "X is the ingredient changing how I think about Y..."',
    pacingNote: 'Deep dive on one ingredient — what it is, how it works, why it matters.',
    emotionalAngle: 'Discovery of a star ingredient.',
    ctaStyle: 'Specific — "look for X on the label, this product has it."',
    proofStyle: 'Single ingredient deep proof — origin, mechanism, and observable effect.',
    detailVi: {
      mechanism: 'Đi sâu vào 1 thành phần ngôi sao ("X là thành phần đang thay đổi mọi thứ"). Tập trung = rõ ràng = ấn tượng sâu.',
      goals: ['Xây thương hiệu cho 1 thành phần', 'Hợp lý hoá sự độc đáo của sản phẩm', 'Khơi gợi tò mò sâu về 1 yếu tố'],
      useCase: ['Sản phẩm có thành phần ngôi sao mạnh', 'Xu hướng thành phần đang lên (NMN, peptide, …)', 'Khán giả niche'],
      example: '"Inulin là thành phần đang âm thầm thay đổi cách chúng ta xử lý đầy hơi."',
    },
  },
  {
    id: 'edu-research-ugc',
    label: 'Research-backed UGC',
    hint: 'Creator + giải thích khoa học',
    glyph: '🎓',
    category: 'educational',
    hookFormula: '"I read a study about this and I had to share..." — creator-as-researcher voice.',
    pacingNote: 'Casual but informative — the creator did the homework so the viewer doesn\'t have to.',
    emotionalAngle: 'Smart-creator authority — trusted because they explained it well.',
    ctaStyle: 'Recommendation — "honestly, I\'d try it after reading this."',
    proofStyle: 'Creator-reported research distilled into one or two plain takeaways.',
    detailVi: {
      mechanism: 'Creator-vai-nhà-nghiên-cứu ("Tôi đọc một nghiên cứu…"). Kết hợp uy quyền + giọng creator — nghiên cứu được "dịch" sang ngôn ngữ TikTok.',
      goals: ['Uy quyền kiểu creator thông minh', 'Niềm tin qua nghiên cứu kiểu thân thiện', 'Vừa giáo dục vừa gần gũi'],
      useCase: ['Khán giả tin creator hơn thương hiệu', 'Sức khoẻ / supplement / chống lão hoá', 'Advertorial nhẹ nhàng'],
      example: '"Tuần trước mình đọc 1 nghiên cứu về sức khoẻ đường ruột — phải chia sẻ liền."',
    },
  },
]

export const SCRIPT_PRESETS: ScriptPreset[] = [...CLASSIC_PRESETS, ...EDUCATIONAL_PRESETS]

export function getPresetById(id: string): ScriptPreset | undefined {
  return SCRIPT_PRESETS.find((p) => p.id === id)
}

// ── Tone modifier chips ─────────────────────────────────────────────────

export const TONE_OPTIONS: ToneOption[] = [
  { id: 'hard-sell',         label: 'Hard sell',          promptHint: 'aggressive sales energy with urgency and direct asks' },
  { id: 'soft-sell',         label: 'Soft sell',          promptHint: 'low-pressure, helpful-friend energy — recommend without pushing' },
  { id: 'emotional',         label: 'Cảm xúc',            promptHint: 'lean into emotional storytelling and vulnerability' },
  { id: 'scientific',        label: 'Khoa học',           promptHint: 'cite mechanism and ingredients with plain-language science' },
  { id: 'funny',             label: 'Hài hước',           promptHint: 'light humour and self-deprecating moments — never cringe' },
  { id: 'luxury',            label: 'Sang trọng',         promptHint: 'premium aspirational tone, refined word choice, calm pacing' },
  { id: 'aggressive-hook',   label: 'Hook gắt',           promptHint: 'sharper, more provocative hook that interrupts the scroll' },
  { id: 'female-audience',   label: 'Nữ',                 promptHint: 'addressing a female viewer — pain points and language framed for her' },
  { id: 'male-audience',     label: 'Nam',                promptHint: 'addressing a male viewer — direct, no-fluff, results-focused' },
  { id: 'older-audience',    label: 'Trung niên',         promptHint: 'older audience (35+) — slower pacing, trust signals, less slang' },
  { id: 'young-tiktok',      label: 'Gen Z TikTok',       promptHint: 'Gen Z TikTok voice — fast cuts, slang, native creator rhythm' },
]
